# ============================================================
# Stage 1: Install dependencies
# ============================================================
FROM node:20-alpine AS deps

# Install libc compatibility for native modules on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package manifests first for layer caching
COPY package.json package-lock.json ./

# Install production + dev deps (needed for build)
RUN npm ci

# ============================================================
# Stage 2: Build the Next.js application
# ============================================================
FROM node:20-alpine AS builder

WORKDIR /app

# Re-use installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy full source
COPY . .

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Ensure public dir always exists (it's optional in Next.js but COPY requires it)
RUN mkdir -p public

# Build with standalone output (set in next.config.mjs)
RUN npm run build

# ============================================================
# Stage 3: Minimal production runner
# ============================================================
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Cloud Run injects PORT=8080 by default; honour it
ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

# Create a non-root user for security best practice
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Standalone build includes its own minimal node_modules
COPY --from=builder /app/public               ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static    ./.next/static

USER nextjs

EXPOSE 8080

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
